@startuml use
'actors
actor "Незарегистрированный пользователь" as UnregisteredUser
actor "Зарегистрированный пользователь" as RegisteredUser
'usecases
usecase "Просмотр ленты" as FeedView
usecase "Зарегистрироваться" as SignUp
usecase "Вход в систему" as LogIn
usecase "Просмотр профиля" as ViewProfile
usecase "Редактирование профиля" as EditProfile
usecase "Просмотр задачи" as ViewTask
usecase "Отправить решение на проверку" as SendResolveOfTask
usecase "Выложить решение в профиль" as SendResolveOfTaskToProfile
usecase "Поиск задачи" as FindTask
usecase "Выбор языка" as ChooseLanguage
usecase "Выбор параметров поиска" as SelectingSearchOptions
usecase "Просмотр статуса решения" as ViewSolutionCharacteristics 
usecase "Посещение чужого профиля" as ViewOtherProfile
usecase "Просмотр чужого решения" as ViewOtherSolution
usecase "Прокомментировать чужое решение" as CommentOtherSolution
usecase "Оценить чужое решение" as EvaluateOtherSolution
'usecases of UnregisteredUser
UnregisteredUser-->FeedView
UnregisteredUser-->SignUp

'usecases of RegisteredUser
RegisteredUser -up-> LogIn
RegisteredUser -->FeedView
RegisteredUser --> ViewProfile
EditProfile .> ViewProfile : extend
RegisteredUser -up-> FindTask
RegisteredUser --> ViewTask
ViewTask .> FeedView : extend
ViewTask .> FindTask : extend
SelectingSearchOptions .> FindTask : extend
SendResolveOfTask .up.> ViewTask : extend
ViewTask.> ChooseLanguage  : include
ViewSolutionCharacteristics .up.> SendResolveOfTask : extend
SendResolveOfTaskToProfile ..> SendResolveOfTask : extend
RegisteredUser --> ViewOtherProfile
ViewOtherSolution ..> ViewOtherProfile : extend
CommentOtherSolution ..> ViewOtherProfile : extend
EvaluateOtherSolution ..> ViewOtherProfile : extend
@enduml
